import test from 'node:test';import assert from 'node:assert/strict';
import {extractMotionRig,validateMotionFrame} from '../src/motion.js';
import {renderAirDancer,addTrails,modelConfig} from '../src/air-dancer-model.js';
import {svgForFrame,countPoints,playbackFrameIndex,pointStats} from '../src/laser.js';
const w=40,h=60,mask=new Uint8Array(w*h);for(let y=5;y<55;y++){const c=20+Math.round(Math.sin(y/8)*3),half=3+Math.floor(y/20);for(let x=c-half;x<=c+half;x++)mask[y*w+x]=1;}for(let x=5;x<20;x++)mask[22*w+x]=1;for(let x=20;x<36;x++)mask[25*w+x]=1;
const motion=extractMotionRig(mask,w,h,{frame:0,timeSeconds:0,sourceColour:{red:240,green:70,blue:40}});
test('motion schema and stable body count',()=>{assert.equal(validateMotionFrame(motion),true);assert.equal(motion.body.length,8);assert.equal(motion.leftArm.length,3);assert.equal(motion.rightArm.length,3)});
test('width extraction and left/right identity',()=>{assert.ok(motion.body.every(p=>p.width>0));assert.ok(motion.leftArm.at(-1).x<motion.rightArm.at(-1).x)});
test('empty mask handled',()=>assert.equal(extractMotionRig(new Uint8Array(w*h),w,h).confidence,0));
test('retargeted model has stable points and RGB SVG',()=>{const a=renderAirDancer(motion),b=renderAirDancer({...motion,frame:1});assert.deepEqual(a.map(s=>s.points.length),b.map(s=>s.points.length));const svg=svgForFrame(a);assert.match(svg,/stroke="rgb\(240 70 40\)"/);assert.doesNotMatch(svg,/<rect/)});
test('trail reduction respects budget',()=>{const frames=[motion,{...motion,frame:1},{...motion,frame:2}],base=renderAirDancer(frames[2]);const reduced=addTrails(frames,2,base,{trailLength:4,budget:countPoints(base)+2});assert.ok(countPoints(reduced)<=countPoints(base)+2)});
test('playback boundaries',()=>{assert.equal(playbackFrameIndex(0,15,2),0);assert.equal(playbackFrameIndex(134,15,2),null)});
test('manifest supporting values',()=>{const strokes=renderAirDancer(motion);const stats=pointStats([{pointCount:countPoints(strokes)},{pointCount:countPoints(strokes)}]);assert.equal(stats.maximum,stats.minimum);assert.equal(modelConfig({palette:'neon'}).stablePathOrder,true)});
