import JSZip from 'https://cdn.jsdelivr.net/npm/jszip@3.10.1/+esm';
import {learnColourModel,trackSelectedSubject} from './subject-tracker.js';
import {extractMotionRig,smoothMotion} from './motion.js';
import {renderAirDancer,addTrails,modelConfig} from './air-dancer-model.js';
import {countPoints,playbackFrameIndex,pointStats,svgForFrame} from './laser.js';
const $=id=>document.getElementById(id),e={videoInput:$('videoInput'),video:$('video'),seek:$('seek'),select:$('selectCanvas'),preview:$('preview'),confirm:$('confirm'),process:$('process'),play:$('play'),download:$('download'),status:$('status'),stats:$('stats'),palette:$('palette'),fps:$('fps'),fpsOut:$('fpsOut'),smoothing:$('smoothing'),smoothOut:$('smoothOut'),trails:$('trails'),trailOut:$('trailOut'),budget:$('budget'),mode:$('mode')};
const s={url:null,box:null,drag:null,model:null,boxSmall:null,motion:[],frames:[],fps:15,playing:null,playStart:0};const ac=document.createElement('canvas'),ax=ac.getContext('2d',{willReadFrequently:true}),sc=e.select.getContext('2d'),pc=e.preview.getContext('2d');
const wait=(target,name)=>new Promise((ok,bad)=>{target.addEventListener(name,ok,{once:true});target.addEventListener('error',bad,{once:true})});
async function seek(t){if(Math.abs(e.video.currentTime-t)>.002){const p=wait(e.video,'seeked');e.video.currentTime=t;await p;}await new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)));}
function drawSelection(mask=null){const r=e.select.getBoundingClientRect();e.select.width=Math.max(1,Math.round(r.width));e.select.height=Math.max(1,Math.round(r.height));sc.clearRect(0,0,e.select.width,e.select.height);if(mask){const img=sc.createImageData(mask.width,mask.height);for(let i=0;i<mask.mask.length;i++)if(mask.mask[i]){img.data[i*4]=80;img.data[i*4+1]=255;img.data[i*4+2]=190;img.data[i*4+3]=110;}const c=document.createElement('canvas');c.width=mask.width;c.height=mask.height;c.getContext('2d').putImageData(img,0,0);sc.drawImage(c,0,0,e.select.width,e.select.height);}if(s.box){sc.strokeStyle='#ffde59';sc.lineWidth=3;sc.strokeRect(s.box.x1,s.box.y1,s.box.x2-s.box.x1,s.box.y2-s.box.y1);}}
function frameData(){ac.width=240;ac.height=Math.max(80,Math.round(240*e.video.videoHeight/e.video.videoWidth));ax.drawImage(e.video,0,0,ac.width,ac.height);return ax.getImageData(0,0,ac.width,ac.height);}
function boxToSmall(box){return{x1:box.x1/e.select.width*ac.width,y1:box.y1/e.select.height*ac.height,x2:box.x2/e.select.width*ac.width,y2:box.y2/e.select.height*ac.height};}
function drawFrame(frame,motion){pc.clearRect(0,0,1000,1000);pc.fillStyle='#020406';pc.fillRect(0,0,1000,1000);for(const st of frame?.strokes??[]){if(st.points.length<2)continue;pc.beginPath();pc.moveTo(st.points[0].x,st.points[0].y);for(const p of st.points.slice(1))pc.lineTo(p.x,p.y);pc.strokeStyle=st.colour;pc.globalAlpha=st.previewOpacity??1;pc.lineWidth=st.width;pc.lineCap='round';pc.lineJoin='round';pc.shadowColor=st.colour;pc.shadowBlur=8;pc.stroke();}pc.globalAlpha=1;pc.shadowBlur=0;if(motion?.body?.length){pc.fillStyle='#fff';for(const p of motion.body){pc.beginPath();pc.arc(p.x*1000,p.y*1000,4,0,Math.PI*2);pc.fill();}}}
e.select.addEventListener('pointerdown',ev=>{const r=e.select.getBoundingClientRect();s.drag={x:ev.clientX-r.left,y:ev.clientY-r.top};s.box={x1:s.drag.x,y1:s.drag.y,x2:s.drag.x,y2:s.drag.y};drawSelection()});e.select.addEventListener('pointermove',ev=>{if(!s.drag)return;const r=e.select.getBoundingClientRect();s.box.x2=ev.clientX-r.left;s.box.y2=ev.clientY-r.top;drawSelection()});addEventListener('pointerup',()=>{if(s.drag){s.drag=null;e.confirm.disabled=false;}});
e.videoInput.addEventListener('change',async ev=>{const file=ev.target.files[0];if(!file)return;if(s.url)URL.revokeObjectURL(s.url);s.url=URL.createObjectURL(file);e.video.src=s.url;await wait(e.video,'loadedmetadata');e.seek.value=0;s.box=null;s.model=null;drawSelection();e.status.textContent='Seek to a clear frame and drag a subject box.'});e.seek.addEventListener('input',async()=>{if(!e.video.duration)return;await seek(e.video.duration*Number(e.seek.value)/1000);drawSelection()});
e.confirm.addEventListener('click',()=>{if(!s.box)return;const image=frameData();s.boxSmall=boxToSmall(s.box);s.model=learnColourModel(image,s.boxSmall);const tracked=trackSelectedSubject(image,s.model,s.boxSmall);drawSelection({mask:tracked.mask,width:image.width,height:image.height});e.process.disabled=tracked.confidence===0;e.status.textContent=tracked.confidence?`Mask preview ready (${Math.round(tracked.confidence*100)}% confidence).`:'No usable mask in the box.'});
e.process.addEventListener('click',async()=>{if(e.mode.value==='person'){e.status.textContent='Legacy person pose remains available on the base branch; v3 processing is intentionally air-dancer only.';return;}const fps=Number(e.fps.value),duration=Math.min(e.video.duration,30),count=Math.max(1,Math.floor(duration*fps)),motion=[],frames=[];let box=s.boxSmall,previous=null;for(let i=0;i<count;i++){await seek(i/fps);const img=frameData(),tracked=trackSelectedSubject(img,s.model,box);box=tracked.box;let rig=extractMotionRig(tracked.mask,img.width,img.height,{frame:i,timeSeconds:i/fps,sourceColour:{red:Math.round(s.model.red),green:Math.round(s.model.green),blue:Math.round(s.model.blue)}});rig.confidence=Math.min(rig.confidence,tracked.confidence);rig=smoothMotion(previous,rig,Number(e.smoothing.value)/100);if(rig.body.length)previous=rig;motion.push(rig);let strokes=renderAirDancer(rig,{palette:e.palette.value,effectStrength:.6});strokes=addTrails(motion,i,strokes,{trailLength:Number(e.trails.value),budget:Number(e.budget.value)});frames.push({index:i,timeSeconds:i/fps,strokes,pointCount:countPoints(strokes)});if(i%3===0)drawFrame(frames[i],rig);e.status.textContent=`Processing ${i+1}/${count}`;}s.motion=motion;s.frames=frames;s.fps=fps;const usable=motion.filter(f=>f.body.length).length,stats=pointStats(frames);e.stats.textContent=`${usable}/${count} usable frames; confidence ${Math.round(motion.reduce((n,f)=>n+f.confidence,0)/count*100)}%; points ${stats.minimum}-${stats.maximum} (avg ${stats.average}).`;e.play.disabled=!usable;e.download.disabled=!usable;drawFrame(frames.find(f=>f.strokes.length),motion.find(f=>f.body.length));e.status.textContent='Motion capture complete.'});
e.play.addEventListener('click',()=>{if(s.playing){cancelAnimationFrame(s.playing);s.playing=null;e.play.textContent='Play';return;}s.playStart=performance.now();e.play.textContent='Stop';const tick=now=>{const i=playbackFrameIndex(now-s.playStart,s.fps,s.frames.length);if(i===null){s.playing=null;e.play.textContent='Play';return;}drawFrame(s.frames[i],s.motion[i]);s.playing=requestAnimationFrame(tick)};s.playing=requestAnimationFrame(tick)});
e.download.addEventListener('click',async()=>{const zip=new JSZip(),root=zip.folder('laser-animation'),folder=root.folder('frames');s.frames.forEach((f,i)=>folder.file(`frame_${String(i).padStart(4,'0')}.svg`,svgForFrame(f.strokes,{frame:i,timeSeconds:f.timeSeconds})));root.file('motion.json',JSON.stringify({formatVersion:1,frames:s.motion},null,2));const settings={palette:e.palette.value,trailLength:Number(e.trails.value),pointBudget:Number(e.budget.value)};root.file('model.json',JSON.stringify(modelConfig(settings),null,2));const usable=s.motion.filter(f=>f.body.length).length;root.file('manifest.json',JSON.stringify({formatVersion:3,sourceFrameRate:null,exportedFrameRate:s.fps,frameCount:s.frames.length,usableFrameCount:usable,pointCountStatistics:pointStats(s.frames),palette:e.palette.value,modelName:'Magic air dancer puppet',trailSetting:Number(e.trails.value),tracking:'user-selected ROI colour fallback (not SAM 2)',colourLimitations:'Solid per-path RGB strokes are exported. Opacity is preview-only; exported trails use solid colour. Gradients and fills are not used.',scannerWarning:'SVG vertices are not scanner points; LaserOS may add interpolation, corner, blanking, and colour-change points.'},null,2));const blob=await zip.generateAsync({type:'blob'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='laser-animation.zip';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)});
for(const [input,out,suffix] of [[e.fps,e.fpsOut,''],[e.smoothing,e.smoothOut,'%'],[e.trails,e.trailOut,'']])input.addEventListener('input',()=>out.value=input.value+suffix);
